### ISSUE TITLE
bindinds for creating KOMO instances are missing

### ISSUE THREAD

**Issue by fdamken** [MarcToussaint/rai-python#5]
The notebooks do not run as expected as attributes such as `ry.Config.komo_path` cannot be found. The corresponding bindings have been removed in commit [7d9ac](https://github.com/MarcToussaint/rai/commit/7d9ac9d757c0ad18310a872c625d0a439a82e844) of rai which is only present on the (stale) branches `marc` and `torch_integration`. However, rai-python references commit [7d1fe](https://github.com/MarcToussaint/rai/commit/7d1fe59db056215d5b6814ab58c760890f4d1902) of RAI which includes said commit removing the `komo*`-bindinds.

This causes shared objects built from this branch to not have those methods. Is it possible to add them back in and/or to synchronize the Python bindinds with RAI's master again?

**Comment by MarcToussaint** [comment]
Hi fdamken. Yes, I refactored the KOMO bindings a bit for the summer term robotics course... I removed older notebooks and just tested the ones remaining. They clarify how to use KOMO as IK or path optimization.
