### ISSUE TITLE
3-IK-optimization

### ISSUE THREAD

**Issue by DrBoil** [MarcToussaint/rai-python#6]
I encountered a problem in 3-IK-optimization module in jupyet-notebook where it calls the command IK.optimize(). The error message says 'libry.KOMO' object has no attribute 'optimize', and it also doesn't seem to be included in rai python API. It would be great if you can provide me with any solution to this.

**Comment by MarcToussaint** [comment]
Hi DrBoil, yes, I refactored the KOMO bindings a bit for the summer term teaching. The optimization is not explicitly called via an NLP_Solver object. I removed older notebooks and tested the new versions, which also exemplify how to use KOMO to define IK or path problems, and how to use NLP_Solver to solve them.
